[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chess-engine"
path = "src/main.rs"

[dependencies]
chrono = "0.4.39"
env_logger = "0.11.6"
log = "0.4.22"
thiserror = "2.0.9"
